#!/bin/bash
#SBATCH --time=24:00:00     # walltime
#SBATCH --nodes=2                                   	# Number of nodes
#SBATCH --ntasks=24        # number of processor cores (i.e. tasks)
#SBATCH --mem-per-cpu=3000M  # memory per CPU core
#SBATCH --job-name="A02_Channel_Period_RotWall"   # job name
#SBATCH --mail-user=marc_julian.rodekamp@tu-dresden.de  # email address (only tu-dresden)
#SBATCH --mail-type=NONE

OUTFILE="Output"

module load release/23.10
module load GCC/11.3.0
module load OpenMPI/4.1.4

module load OpenFOAM/10

source $FOAM_BASH


srun topoSet > "$OUTFILE"
# srun decomposePar -latestTime > "$OUTFILE"
srun rhoSimpleFoam -parallel > "$OUTFILE"







